server:
  port: 8888
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: paycenter
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    database: 1
    password:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cmx?useUnicode=true&amp;characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: cmx123
    initialSize: 1
    maxActive: 50
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,slf4j
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cmx.chatserver.security.model
shiro:
  algorithm:
    name: md5
  hash:
    iterators: 1
  maxpassword:
    retrytime: 5